### ISSUE TITLE
JaCoCo format support

### ISSUE THREAD

**Issue by toshi0607** [k1LoW/octocov#148]
Hello, thank you for creating a great tool! We are considering introducing octocov. I'd like to confirm if JaCoCo will be supported (or how we implement a patch for JaCoCo). This is because we are using JaCoCo for Java workload, and [clover](https://bitbucket.org/atlassian/clover/src/master/) and [cobertura](https://github.com/cobertura/cobertura) that are supported by octocov seems not to be actively developed.

**Comment by k1LoW** [comment]
Hi! JaCoCo is not yet supported.
However, I saw your comment and wanted to support JaCoCo.

**Comment by k1LoW** [comment]
octocov now supports JaCoCo in v0.39.1.

There is still room for improvement in the calculation of covered instructions and missed instructions, but it is now at the point where coverage can be collected first.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/57114/161425593-6debbf10-648e-4f92-b82a-99ee85b577cb.png">

**Comment by toshi0607** [comment]
Thank you for supporting JaCoCo sooo quickly!!! I will test it with our product.

**Comment by k1LoW** [comment]
If it works fine in your environment, I would be happy to close this Issue.

If it doesn't work, questions are welcome 🌟

**Comment by toshi0607** [comment]
Hi, I stated testing with this PR! https://github.com/ubie-oss/kotlin-graphql-sample/pull/19
I'd like to ask two questions.

1. Is there limitation finding PR number?

octocov found the coverage file, but it doesn't comment on the PR. Is commenting a draft PR supported?

```
octocov version 0.3[9](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:9).1
Skip measuring code to test ratio: codeToTestRatio: is not set
Generate coverage report badge...

                         feature/introduce-octocov     
                                 (445a1d7)             
-------------------------------------------------------
  Coverage                                       6.0%  
  Test Execution Time                             26s  

Skip commenting report to pull request: could not detect number of pull request
Skip storing the report: the condition in the `if` section is not met (is_default_branch)
Skip pushing generate files: the condition in the `if` section is not met (is_default_branch)
```

2. Is local execution for JaCoCo supported?

When I test with `./gradlew test jacocoTestReport` and the test report exists in `build/reports/jacoco/test/`, does `octocov` work?

```console
$ ls buls build/reports/jacoco/test/
html                 jacocoTestReport.xml

$ octocov
Skip measuring code coverage: 2 errors occurred:
        * parsable coverage report not found: /Users/toshi0607/dev/ubie/kotlin-graphql-sample
        * octocov report.json not found: /Users/toshi0607/dev/ubie/kotlin-graphql-sample


Error: nothing could be measured
```

**Comment by k1LoW** [comment]
> 1. Is there limitation finding PR number?

octocov finds PR number in two patterns.

1. when called by `on.pull_request:`.
2. when called by `on.push:`, if associated with a PR at the time of its workflow execution.

1 certainly detects the PR number.
2 requires the PR to have been created before the step is executed

> 2. Is local execution for JaCoCo supported?

Could you run octocov with DEBUG=1 set and show me its output?

```console
$ DEBUG=1 octocov
```

**Comment by toshi0607** [comment]
Thank you for the reply!

## PR  number

I confirmed our case is the second pattern, `on.push:`. After creating a PR, I added several commits. However octocov-action doesn't put a comment on the PR. May I share the config files and build logs?

.octocov.yml
```yaml
# generated by octocov init
coverage:
  badge:
    path: docs/coverage.svg
push:
  if: is_default_branch
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
```

.github/workflows/build.yml
```yaml
name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Build
        run: |
          ./gradlew ktlintCheck bootJar --no-daemon --max-workers 2
      - name: Test
        run: |
          ./gradlew test jacocoTestReport --no-daemon --max-workers 2
      - name: Coverage
        uses: k1LoW/octocov-action@v0

      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-report
          path: build/reports/jacoco/test
```

<details>
<summary>Build log</summary>

```
Run k1LoW/octocov-action@v0
  with:
    github-token: ***
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
/usr/bin/docker run --name bcf099[2](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:2)742ba0efa9489b8be5e[3](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:3)f1c75e[4](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:4)6[5](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:5)7_1cfb8e --label 2bcf09 --workdir /github/workspace --rm -e JAVA_HOME -e INPUT_GITHUB-TOKEN -e INPUT_CONFIG -e OCTOCOV_GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/kotlin-graphql-sample/kotlin-graphql-sample":"/github/workspace" 2bcf09:92742ba0efa9489b8be5e3f1c75e4[6](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:6)5[7](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:7)
octocov version 0.3[9](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:9).1
Skip measuring code to test ratio: codeToTestRatio: is not set
Generate coverage report badge...

                         feature/introduce-octocov     
                                 (445a1d7)             
-------------------------------------------------------
  Coverage                                       6.0%  
  Test Execution Time                             26s  

Skip commenting report to pull request: could not detect number of pull request
Skip storing the report: the condition in the `if` section is not met (is_default_branch)
Skip pushing generate files: the condition in the `if` section is not met (is_default_branch)
```
</details>

[PR](https://github.com/ubie-oss/kotlin-graphql-sample/pull/19)

## Local execution

I'm sorry... The version of octocov was old (0.38.0). It worked well after upgrading to 0.39.1!

```console
$ DEBUG=1 octocov
2022/04/11 10:07:13 parse as Go coverage: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/coverage.out: no such file or directory
2022/04/11 10:07:13 parse as LCOV: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/lcov.info: no such file or directory
2022/04/11 10:07:13 parse as SimpleCov: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/.resultset.json: no such file or directory
2022/04/11 10:07:13 parse as Clover: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/coverage.xml: no such file or directory
2022/04/11 10:07:13 parse as Cobertura: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/coverage.xml: no such file or directory

              feature/introduce-octocov     
                      (445a1d7)             
--------------------------------------------
  Coverage                            6.0%
```

**Comment by toshi0607** [comment]
Thank you for the reply!

## PR  number

I confirmed our case is the second pattern, `on.push:`. After creating a PR, I added several commits. However octocov-action doesn't put a comment on the PR. May I share the config files and build logs?

.octocov.yml
```yaml
# generated by octocov init
coverage:
  badge:
    path: docs/coverage.svg
push:
  if: is_default_branch
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
```

.github/workflows/build.yml
```yaml
name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Build
        run: |
          ./gradlew ktlintCheck bootJar --no-daemon --max-workers 2
      - name: Test
        run: |
          ./gradlew test jacocoTestReport --no-daemon --max-workers 2
      - name: Coverage
        uses: k1LoW/octocov-action@v0

      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-report
          path: build/reports/jacoco/test
```

<details>
<summary>Build log</summary>

```
Run k1LoW/octocov-action@v0
  with:
    github-token: ***
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
/usr/bin/docker run --name bcf099[2](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:2)742ba0efa9489b8be5e[3](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:3)f1c75e[4](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:4)6[5](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:5)7_1cfb8e --label 2bcf09 --workdir /github/workspace --rm -e JAVA_HOME -e INPUT_GITHUB-TOKEN -e INPUT_CONFIG -e OCTOCOV_GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/kotlin-graphql-sample/kotlin-graphql-sample":"/github/workspace" 2bcf09:92742ba0efa9489b8be5e3f1c75e4[6](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:6)5[7](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:7)
octocov version 0.3[9](https://github.com/ubie-oss/kotlin-graphql-sample/runs/5961469863?check_suite_focus=true#step:7:9).1
Skip measuring code to test ratio: codeToTestRatio: is not set
Generate coverage report badge...

                         feature/introduce-octocov     
                                 (445a1d7)             
-------------------------------------------------------
  Coverage                                       6.0%  
  Test Execution Time                             26s  

Skip commenting report to pull request: could not detect number of pull request
Skip storing the report: the condition in the `if` section is not met (is_default_branch)
Skip pushing generate files: the condition in the `if` section is not met (is_default_branch)
```
</details>

[PR](https://github.com/ubie-oss/kotlin-graphql-sample/pull/19)

## Local execution

I'm sorry... The version of octocov was old (0.38.0). It worked well after upgrading to 0.39.1!

```console
$ DEBUG=1 octocov
2022/04/11 10:07:13 parse as Go coverage: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/coverage.out: no such file or directory
2022/04/11 10:07:13 parse as LCOV: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/lcov.info: no such file or directory
2022/04/11 10:07:13 parse as SimpleCov: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/.resultset.json: no such file or directory
2022/04/11 10:07:13 parse as Clover: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/coverage.xml: no such file or directory
2022/04/11 10:07:13 parse as Cobertura: stat /Users/toshi0607/dev/ubie/kotlin-graphql-sample/coverage.xml: no such file or directory

              feature/introduce-octocov     
                      (445a1d7)             
--------------------------------------------
  Coverage                            6.0%
```
