### ISSUE TITLE
unable to fetch result from a private repo under the same org in central mode.

### ISSUE THREAD

**Issue by abhijit-nightfall** [k1LoW/octocov#297]
**Central Repo Config**
.octocov.yml
```
timeout: 60sec
central:
  reports:
    datastores:
      - artifact://org/repo-1
      - artifact://org/repo-2
  push:
    enable: true
  reReport:
    enable: true
  summary:
    if: true
```
    
**Repo-1 Config**
.octocov.yml
```
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
push:
  if: is_default_branch
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
```

**No Error in the Logs but the readme gets updated with a blank result -** 
<img width="716" alt="Screenshot 2023-11-02 at 6 57 54 PM" src="https://github.com/k1LoW/octocov/assets/127822984/e6b234ad-159a-4b4d-aa12-a5d9a0462b14">
