### ISSUE TITLE
octocov didn't comment on the pull request

### ISSUE THREAD

**Issue by sthusm** [k1LoW/octocov#397]
I use rspec, here is my octocov.yml file
```
coverage:
  paths:
    - coverage/.resultset.json
codeToTestRatio:
  code:
    - '**/*.rb'
    - '!**/*_spec.rb'
  test:
    - '**/*_spec.rb'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: true
  deletePrevious: true
summary:
  if: true
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

```
everything goes well during the CI, but no comment is added to the PR. an error also occurs if you look at the logs

```
octocov version 0.56.3
---------------------------------------
  Coverage                      42.7%  
  Code to Test Ratio            1:0.1  

Commenting report...
Skip commenting report to pull request: context deadline exceeded
Adding report to job summary page...
Skip adding report to job summary page: context deadline exceeded
Skip inserting report to body of pull request: body: is not set
Storing report...
Skip pushing generate files: push: is not set
```

**Comment by k1LoW** [comment]
> context deadline exceeded

Something seems to be taking a long time.

**Comment by k1LoW** [comment]
https://github.com/k1LoW/octocov/blob/da021e789c50fe0ac17bb4e695094e09decfe924/gh/gh.go#L45

**Comment by sthusm** [comment]
hmm, i don`t think so. How can i get more logs?

**Comment by sthusm** [comment]
Yeah, it took 1m 37s last time. Can i change default value for timeout?

**Comment by k1LoW** [comment]
You can use `timeout:` section.

```
timeout: 5min
coverage:
  paths:
    - coverage/.resultset.json
codeToTestRatio:
  code:
    - '**/*.rb'
    - '!**/*_spec.rb'
  test:
    - '**/*_spec.rb'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: true
  deletePrevious: true
summary:
  if: true
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
```
