### ISSUE TITLE
Can I overwrite coverage.path in the config with any command line option?

### ISSUE THREAD

**Issue by lufia** [k1LoW/octocov#406]
# motivation

In GitHub Actions reusable workflow, we likely combine two phases: run `go test -coverprofile=out` then collect coverage report.

For example:

```yml
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - run: go test -race -covermode=atomic -coverprofile=prof.out ./...
      shell: bash
    - k1LoW/octocov-action@v1
```

In this situation, I think, there is a structural problem.

1. **.octocov.yml** may be stored on the caller repository
2. on the other hand, resuable workflow will likely be stored another repository, such as **octocat/workflows**
3. so we must sync coverage.report paths in the two or more repositories:
    - `go test` of the reusable workflow
    - **.octocov.yml** for each repository

**Comment by k1LoW** [comment]
> overwrite coverage.path in the config with any command line option

First, at this time we do not have the option you seek.

Next, what about using environment variables in .octocov.yml as a solution that can be used at this time?

`${GITHUB_WORKSPACE}.octocov.yml` or `${GITHUB_WORKSPACE:-default_path}.octocov.yml`

**Comment by k1LoW** [comment]
The `-r` option may be used to specify a single coverage report path.

**Comment by lufia** [comment]
Hi! Thanks for your response.
I tried that both approaches.

### The way to use environment variables

I wrote octo cov.yml as below:

```yaml
coverage:
  paths:
  - ${COVERPROFILE_PATH}
  - cover.out
codeToTestRatio:
  ...
```

In above case, I got expected result if *COVERPROFILE_PATH* is set. However, if the env is not set, octocov couldn't parse octocov.yml

### The way to specify  the report path with -r option

Perfect!

I wrote octocov.yml as below:

```yaml
coverage:
  paths:
  - cover.out
codeToTestRatio:
  ...
```

Then I ran octocov

```sh
go test -coverprofile=out
octocov -r out
```

The `-r` option is the option I desired.

So, I want the way for octocov-action to specify `-r` option.
Is it acceptable to make octocov-action to be able to receive -r option?
