### ISSUE TITLE
[Question] Is there any way to exclude specific directories from coverage?

### ISSUE THREAD

**Issue by hiromaily** [k1LoW/octocov#459]
When executing `octocov ls-files` command, result always include files that I wanna exclude.

Though I tried to exclude files using `.octocov.yml` as the following, it doesn't work.
In this case, I wanna exclude any files which is contained in mocks directories.

```
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
    - '!**/mocks/**/*.go'
  test:
    - '**/*_test.go'
    - '!**/mocks/**/**/*_test.go'
```

Could you give me right instructions?
Thanks.

**Comment by k1LoW** [comment]
Hi @hiromaily. Thank you for your question.

You can use [`coverage.exclude:`](https://github.com/k1LoW/octocov?tab=readme-ov-file#coverageexclude) 👍 

```yaml
coverage:
  exclude:
    - '**/mocks/**/*.go'
 ```
